version: '3.1'

volumes:
  mapper_db_vol:

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=mapper
      - POSTGRES_PASSWORD=mapper
    volumes:
      - mapper_db_vol:/var/lib/postgresql/data
    ports:
      - '5432:5432'
